### PR TITLE
Navbar

### PR DESCRIPTION
**Pull request by jorbush**
image
image

### CODE REVIEW

**Comment by mriverre8** [comment]
Its perfectly implemented but i think that the entire column on color blue is so simple, maybe i would add some div inside the column with a padding of X, not too big, wrapping the items inside with a h-full. If you see it propperly i will approve the PR

Something like this:
image
image

**Comment by jorbush** [comment]
> Its perfectly implemented but i think that the entire column on color blue is so simple, maybe i would add some div inside the column with a padding of X, not too big, wrapping the items inside with a h-full. If you see it propperly i will approve the PR
> 
> 
> 
> Something like this:
> 
> image
> 
> image
> 
> 

I personally do not like the proposed design. Thank you for your time. Maybe if you want and you are free (when you have finished the Cypress issue), you can change the design if you want 😺

**Comment by jorbush** [comment]
But for me, this design is better right now

**Review by mriverre8 — APPROVED** [review]
👍👍

**Pull request merged**
